apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-tls
spec:
  secretName: blog-tls
  dnsNames:
  - <domain-name>
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - <domain-name>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer